server:
  port: 80

spring:
  devtools:
    restart:
      enabled: true

  datasource:
    username: "sergiu"
    password: "centrala"
    url: "jdbc:mysql://localhost:3306/test?serverTimezone=UTC"

  jpa:
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    hibernate:
      ddl-auto: "update"
